language: python

branches:
  only:
    - master
    - homework-ci

services:
  - docker

before_install:
  - docker pull selenium/standalone-chrome
  - docker run -d selenium/standalone-chrome bash

script:
  - ls -la
