language: python

branches:
  only:
    - master
    - homework-ci

services:
  - docker

before_install:
  - docker pull selenium/standalone-chrome
  - docker run -d selenium/standalone-chrome bash

script:
  - sudo apt-get update -y
  - sudo apt-get install python3-pip -y
  - python3 -mpip install -r requirements.txt
  - sudo Xvfb :99 -ac &
  - sudo python3 -mpytest ./homework-ci/test_todo_mvc.py

