language: python
python:
  - '3.6'

branches:
  only:
    - master
    - homework-ci

dist: trusty
addons:
  chrome: stable
before_install:
  - # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost

install:
  - pip install -r requirements.txt

script:
  - python3 -mpytest ./smoke/todo_mvc_test.py
