FROM python:3.6

RUN git clone --progress --verbose https://github.com/alsam1992/otus-qa-course.git ./app

WORKDIR /app

RUN pip install -r requirements.txt

ENV CHROMEDRIVER_VERSION 2.19
ENV CHROMEDRIVER_DIR /app


RUN apt-get install -yqq unzip
RUN wget -O /tmp/chromedriver.zip http://chromedriver.storage.googleapis.com/`curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE`/chromedriver_linux64.zip
RUN unzip /tmp/chromedriver.zip chromedriver -d /app

RUN curl https://dl-ssl.google.com/linux/linux_signing_key.pub -o /tmp/google.pub \
    && cat /tmp/google.pub | apt-key add -; rm /tmp/google.pub \
    && echo 'deb http://dl.google.com/linux/chrome/deb/ stable main' > /etc/apt/sources.list.d/google.list \
    && mkdir -p /usr/share/desktop-directories \
    && apt-get -y update && apt-get install -y google-chrome-stable

ENV PATH $CHROMEDRIVER_DIR:$PATH